[Fix] utils as_table when sort_headers=False
AttributeError: 'dict_keys' object has no attribute 'remove'

When sort_headers=False headers need to be a list to call remove()

Signed-off-by: Olivier DRAGHI <odraghi@gmail.com>